### ISSUE TITLE
Update documentation to sound cool

### ISSUE THREAD

**Issue by bbourqu** [hackinginformation/dotfiles#17]
Under NVim install change:
`cd ~/.config/nvim && mkdir colors undo swap spell backup && cd -`
to
`cd $_ && mkdir colors undo swap spell backup && cd -`

**Comment by challsted** [comment]
Sounding cool vs allowing the user to know what the purpose is....

**Comment by bbourqu** [comment]
Close it for now
On Jan 15, 2016 7:36 AM, Chase notifications@github.com wrote:Sounding cool vs allowing the user to know what the purpose is....
