### ISSUE TITLE
v2.2 - All calls to UTF-8 are "errors"

### ISSUE THREAD

**Issue by challsted** [hackinginformation/dotfiles#9]
Need to investigate why the current dev version thinks that UTF-8 is bad, add it back once i get it figured out, or tweek it to use what ever the new way of doing it is.

**Comment by bbourqu** [comment]
I'm using 2.1 and its not throwing such errors

**Comment by challsted** [comment]
Not having these issues in 2.1+, dropping support for pre 2.0
